PREFIX chembl: <http://rdf.ebi.ac.uk/terms/chembl#>
PREFIX cheminf: <http://semanticscience.org/resource/>
PREFIX chembl_mol: <http://rdf.ebi.ac.uk/resource/chembl/molecule/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <https://schema.org/>

CONSTRUCT
{
  ?s a schema:Protein ;
     schema:alternateName ?altName ;
     schema:hasRepresentation ?sequence ;
     schema:hasBioPolymerSequence ?sequence ;
     schema:sameAs ?sameAs ;
     schema:hasBioChemInteraction ?molecule .
}
WHERE
{
	VALUES ?s { @_MOLS_@ }
	
	?s a chembl:SingleProtein .
       
	?s chembl:hasTargetComponent ?targetComponent .
       
	?targetComponent chembl:proteinSequence ?sequence ;
                   skos:altLabel ?altName ;
                   skos:exactMatch ?sameAs .
				 
	?s chembl:hasAssay [ chembl:hasActivity [
								chembl:hasMolecule ?molecule
							]
						]
}
