PREFIX chembl: <http://rdf.ebi.ac.uk/terms/chembl#>
PREFIX cheminf: <http://semanticscience.org/resource/>
PREFIX chembl_mol: <http://rdf.ebi.ac.uk/resource/chembl/molecule/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <https://schema.org/>


CONSTRUCT 
{
  ?s a schema:MolecularEntity.
  ?s schema:biologicalRole ?indication.
  ?s schema:bioChemInteraction ?target.

}
WHERE
{
  VALUES ?s { @_MOLS_@ }
  
  ?s a chembl:SmallMolecule.

  OPTIONAL{
	?s chembl:hasActivity [ a chembl:Activity;
							chembl:hasAssay [ a chembl:Assay;
												chembl:hasTarget ?target]].
	?target a chembl:SingleProtein.
  }
  
  OPTIONAL{
	?s chembl:hasDrugIndication [ a chembl:DrugIndication; 
									chembl:hasMeshHeading ?indication].
  }
} 